framework:
    secret: "%env(APP_SECRET)%"
    csrf_protection: true
    session:
        handler_id: ~
    php_errors:
        log: true
    assets:
        version_strategy: Ruwork\RuworkBundle\Asset\VersionStrategy\FilemtimeStrategy
