httplug:
    main_alias:
        client: httplug.client.guzzle6
        message_factory: httplug.message_factory.default
        uri_factory: httplug.uri_factory.default
        stream_factory: httplug.stream_factory.default

    classes:
        client: Http\Adapter\Guzzle6\Client
        message_factory: Http\Message\MessageFactory\GuzzleMessageFactory
        uri_factory: Http\Message\UriFactory\GuzzleUriFactory
        stream_factory: Http\Message\StreamFactory\GuzzleStreamFactory

    profiling:
        captured_body_length: 1000

    discovery:
        client: httplug.client.guzzle6
        async_client: httplug.client.guzzle6

    clients:
        guzzle6:
            factory: httplug.factory.guzzle6
            plugins:
                - httplug.plugin.content_length

services:
    Http\Client\HttpClient: "@httplug.client.guzzle6"
    Http\Client\HttpAsyncClient: "@httplug.client.guzzle6"
