security:
    providers:
        entity_user:
            entity:
                class: App\Entity\User\User

    encoders:
        App\Entity\User\User:
            algorithm: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: entity_user
            anonymous: true
            manual: ~
            remember_me:
                secret: "%env(APP_SECRET)%"
                always_remember_me: true
            logout:
                path: logout
                target: index
            switch_user:
                role: ROLE_CAN_IMPERSONATE
                parameter: _impersonate

    role_hierarchy:
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN

    access_control:
        #- { path: ^(/en)?/admin, roles: ROLE_ADMIN }
        #- { path: ^(/en)?/profile, roles: IS_AUTHENTICATED_REMEMBERED }
