language: php

sudo: false

addons:
    ssh_known_hosts: []
    postgresql: 9.6

cache:
    yarn: true
    directories:
        - node_modules
        - $HOME/.composer/cache/files

php: 7.1

env:
    global:
        - APP_ENV=dev
        - APP_SECRET=91833b796aac7eaa2e5666c814da19d3
        - DATABASE_URL="pgsql://postgres@localhost:5432/project?charset=utf8&serverVersion=9.6"
        - MAILER_URL=null://localhost

install:
    - composer install --no-scripts --no-interaction
    - touch config/parameters.yaml

script:
    - vendor/bin/php-cs-fixer fix --dry-run --using-cache=no -vvv
    - vendor/bin/security-checker security:check --end-point=http://security.sensiolabs.org/check_lock --no-interaction
    - bin/console cache:warmup --no-interaction
    - bin/console lint:twig templates/ --env=prod --no-interaction
    - bin/console doctrine:database:create --no-interaction
    - bin/console doctrine:migrations:migrate --allow-no-migration --no-interaction
    - bin/console doctrine:schema:validate --env=prod --no-interaction

deploy:
    skip_cleanup: true
    provider: script
    script: vendor/bin/dep deploy -vv
    on:
        branch: master

notifications:
    webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
