language: php

sudo: false

addons:
    postgresql: 9.6
    ssh_known_hosts: []

cache:
    yarn: true
    directories:
        - $HOME/.composer/cache/files
        - $HOME/.php_cs
        - node_modules

php: 7.1

env:
    global:
        - APP_ENV=dev
        - APP_SECRET=secret
        - DATABASE_URL="pgsql://postgres@localhost:5432/project?charset=utf8&serverVersion=9.6"

install:
    - composer install --no-scripts --no-interaction
    - touch config/parameters.yaml

script:
    - vendor/bin/security-checker security:check --end-point=http://security.sensiolabs.org/check_lock --no-interaction
    - vendor/bin/php-cs-fixer fix --dry-run --cache-file=$HOME/.php_cs/.cache -vvv
    - bin/console cache:warmup --no-interaction
    - bin/console lint:yaml config --parse-tags --env=prod --no-interaction
    - bin/console lint:yaml fixtures --parse-tags --env=prod --no-interaction
    - bin/console lint:yaml translations --parse-tags --env=prod --no-interaction
    - bin/console lint:twig templates/ --env=prod --no-interaction
    - bin/console doctrine:database:create --no-interaction
    - bin/console doctrine:migrations:migrate --allow-no-migration --no-interaction
    - bin/console doctrine:schema:validate --env=prod --no-interaction

deploy:
    skip_cleanup: true
    provider: script
    script: vendor/bin/dep deploy -vv
    on:
        branch: master

notifications:
    webhooks:
        urls: https://fathomless-fjord-24024.herokuapp.com/notify?secret=
        on_cancel: never
