monolog:
    handlers:
        stream:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            channels: ['!event']
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
