monolog:
    handlers:
        fingers_crossed:
            type: fingers_crossed
            action_level: error
            handler: fingers_crossed.group
            excluded_http_codes: [403, 404]
        fingers_crossed.group:
            type: group
            members:
                - stream
                - sentry.buffer
        stream:
            type: service
            id: app.prod.easy_log.main
        sentry.buffer:
            type: buffer
            handler: sentry
        sentry:
            type: raven
            dsn: "%sentry.dsn%"
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine']

services:
    app.prod.easy_log.main:
        class: EasyCorp\EasyLog\EasyLogHandler
        arguments:
            $stream: "%kernel.logs_dir%/%kernel.environment%.log"
