ruvents_admin:
    list:
        types_template: admin/list_field_types.html.twig

    forms:
        default_theme: admin/forms.html.twig
        type_aliases:
            ckeditor: Ivory\CKEditorBundle\Form\Type\CKEditorType

    menu:
        -
            title: На сайт
            route: index
            attributes: { target: _blank, icon: fa-home }
        -
            title: Пользователи
            attributes: { icon: fa-users }
            active: "entity === 'user'"
            children:
                - { title: Список, entity: 'user:list', active: "entity === 'user'" }

    entities:
        user:
            class: App\Entity\User\User
            list:
                title: Список пользователей
                fields:
                    - '@id'
                    - email{Email}
                    - roles{Роли}
                    - '@actions'
            create: false
            edit:
                title: Редактирование пользователя
                fields:
                    - email{Email}
                    -
                        name: roles
                        type: choice
                        #requires_granted:
                        #    - ROLE_SUPER_ADMIN
                        options:
                            label: Роли
                            multiple: true
                            choices:
                                ROLE_USER: ROLE_USER
                                ROLE_ADMIN: ROLE_ADMIN
                                ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN
                                ROLE_CAN_IMPERSONATE: ROLE_CAN_IMPERSONATE
