parameters:
    liip_imagine.root: "%kernel.project_dir%/public"
    router.request_context.base_url: ''
    router.request_context.host: localhost
    router.request_context.scheme: http
    runet_id.clients: { default: { key: "%runet_id.key%", secret: "%runet_id.secret%" } }
    runet_id.default_client: default
    runet_id.key: key
    runet_id.secret: secret
    sentry.dsn: null
    swiftmailer.dev.delivery_address: test@test.test
    swiftmailer.dev.sender_address: test@test.test
