_controllers:
    resource: ../src/Controller/
    type: annotation
    defaults:
        _locale: "%locale%"
    requirements:
        _locale: "%locales_pattern%"
    options:
        prefix_variable: _locale

about: &static
    path: /about
    defaults: &static_defaults
        _controller: ruwork_template_i18n.controller
        _locale: "%locale%"
        template: about.html.twig
    requirements:
        _locale: "%locales_pattern%"
    options:
        prefix_variable: _locale

#new:
#    <<: *static
#    path: /new
#    defaults:
#        <<: *static_defaults
#        template: index.html.twig

logout:
    path: /logout

_admin:
    prefix: /admin
    resource: '@RuventsAdminBundle/Resources/config/routes.php'

_upload_download:
    prefix: /download
    resource: "@RuworkUploadBundle/Resources/config/download_route.yaml"
    defaults:
        class: App\Entity\Upload

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

_remove_trailing_slash:
    resource: "@RuworkRoutingToolsBundle/Resources/config/routes.php"
