_controllers:
    resource: ../src/Controller/
    type: annotation
    prefix: &prefix
        ru: /
        en: /en

_pages:
    resource: pages.yaml
    prefix: *prefix

logout:
    path: /logout

_admin:
    resource: "@RuventsAdminBundle/Resources/config/routes.php"
    prefix: /admin

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"
