imports:
    - { resource: 'parameters.default.yaml' }
    - { resource: 'parameters.yaml' }

parameters:
    locale: ru
    locales: [ru, en]
    locales_pattern: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            #$debug: "%kernel.debug%"
            #$defaultLocale: "%kernel.default_locale%"
            #$environment: "%kernel.environment%"
            #$projectDir: "%kernel.project_dir%"
            #$publicDir: "%kernel.project_dir%/public"

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller/*'
        public: true

    App\Feature\MetricsFeature:
        $available: "%feature.metrics%"
