imports:
    - { resource: 'parameters.default.yaml' }
    - { resource: 'parameters.yaml' }
    - { resource: 'admin.yaml' }

parameters:
    locale: ru
    locales: [ru, en]

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
